// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.bs.js");
var Authenticator$ReactTemplate = require("./Authenticator/Authenticator.bs.js");
var MessageSender$ReactTemplate = require("./MessageSender.bs.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var path = param[/* state */2];
      var tmp;
      var exit = 0;
      if (path) {
        switch (path[0]) {
          case "authenticate" : 
              if (path[1]) {
                exit = 1;
              } else {
                tmp = ReasonReact.element(/* None */0, /* None */0, Authenticator$ReactTemplate.make(/* array */[]));
              }
              break;
          case "send_message" : 
              if (path[1]) {
                exit = 1;
              } else {
                tmp = ReasonReact.element(/* None */0, /* None */0, MessageSender$ReactTemplate.make(/* array */[]));
              }
              break;
          default:
            exit = 1;
        }
      } else {
        tmp = React.createElement("div", undefined, "nothing to see");
      }
      if (exit === 1) {
        tmp = React.createElement("div", undefined, "Not found!");
      }
      return React.createElement("div", undefined, React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make("/", /* array */["Home"])), ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make("send_message", /* array */["Send Message"])), ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make("authenticate", /* array */["Authenticate"]))), tmp);
    });
  newrecord[/* initialState */10] = (function () {
      return /* [] */0;
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [action]);
    });
  newrecord[/* subscriptions */13] = (function (self) {
      return /* :: */[
              /* Sub */[
                (function () {
                    return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                  return Curry._1(self[/* send */4], url[/* path */0]);
                                }));
                  }),
                ReasonReact.Router[/* unwatchUrl */2]
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
