// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function onChangeToAction(action, evt) {
  var new_value = evt.target.value;
  Curry._1(action, new_value);
  return /* () */0;
}

function ste(prim) {
  return prim;
}

exports.onChangeToAction = onChangeToAction;
exports.ste = ste;
/* No side effect */
